kind: Banana
apiVersion: konf.io/v1alpha1
name: integration
version: 1.0.0
clusters:
- name: hubble-experiments
  version: 2.4.5
  ingress: 
    urlFormat: "$1-$2.k8s.mdlwr.com"
modules:
- name: ingress/nginx
  opts: {}