kind: Banana
apiVersion: konf.io/v1alpha1
modules:
# - name: monitoring/grafana
#   version: v1.0.0
# - name: ingress/nginx
#   components:
#   - tls
#   - loadbalancer
- name: networking/infoblox
  version: v1.0.0
  components:
  - service/nodeport
  secrets:
  - INFOBLOX_USERNAME=admin
  - INFOBLOX_PASSWORD=password
- name: logging/loki
  component:
  - minio
