kind: Banana
apiVersion: konf.io/v1alpha1
name: integration
version: 1.0.0
modules:
- name: https://github.com/sighupio/fury-kubernetes-ingress//katalog/nginx
- name: https://github.com/sighupio/fury-kubernetes-ingress//katalog/cert-manager
- name: https://github.com/sighupio/fury-kubernetes-ingress//katalog/forecastle
