kind: Banana
apiVersion: konf.io/v1alpha1
modules:
- name: monitoring/grafana
  namespace: grafana
  components:
  - dashboards/kubernetes/apiserver
  - dashboards/kubernetes/controller-manager
  - dashboards/kubernetes/resources/pod